/*===- TableGen'erated file -------------------------------------*- C++ -*-===*\
|*                                                                            *|
|* Intrinsic Function Source Fragment                                         *|
|*                                                                            *|
|* Automatically generated file, do not edit!                                 *|
|*                                                                            *|
\*===----------------------------------------------------------------------===*/

#ifndef LLVM_IR_INTRINSIC_SPV_ENUMS_H
#define LLVM_IR_INTRINSIC_SPV_ENUMS_H

namespace llvm::Intrinsic {

enum SPVIntrinsics : unsigned {
// Enum values for intrinsics.
    spv_abort = 13183,                                 // llvm.spv.abort (IntrinsicsSPIRV.td:44)
    spv_all,                                   // llvm.spv.all (IntrinsicsSPIRV.td:100)
    spv_all_memory_barrier,                    // llvm.spv.all.memory.barrier (IntrinsicsSPIRV.td:178)
    spv_all_memory_barrier_with_group_sync,    // llvm.spv.all.memory.barrier.with.group.sync (IntrinsicsSPIRV.td:179)
    spv_alloca,                                // llvm.spv.alloca (IntrinsicsSPIRV.td:45)
    spv_alloca_array,                          // llvm.spv.alloca.array (IntrinsicsSPIRV.td:46)
    spv_any,                                   // llvm.spv.any (IntrinsicsSPIRV.td:101)
    spv_assign_aliasing_decoration,            // llvm.spv.assign.aliasing.decoration (IntrinsicsSPIRV.td:359)
    spv_assign_decoration,                     // llvm.spv.assign.decoration (IntrinsicsSPIRV.td:19)
    spv_assign_fpmaxerror_decoration,          // llvm.spv.assign.fpmaxerror.decoration (IntrinsicsSPIRV.td:362)
    spv_assign_name,                           // llvm.spv.assign.name (IntrinsicsSPIRV.td:18)
    spv_assign_ptr_type,                       // llvm.spv.assign.ptr.type (IntrinsicsSPIRV.td:17)
    spv_assign_type,                           // llvm.spv.assign.type (IntrinsicsSPIRV.td:16)
    spv_assume,                                // llvm.spv.assume (IntrinsicsSPIRV.td:66)
    spv_atomic_load,                           // llvm.spv.atomic.load (IntrinsicsSPIRV.td:28)
    spv_atomic_store,                          // llvm.spv.atomic.store (IntrinsicsSPIRV.td:30)
    spv_bitcast,                               // llvm.spv.bitcast (IntrinsicsSPIRV.td:36)
    spv_cmpxchg,                               // llvm.spv.cmpxchg (IntrinsicsSPIRV.td:42)
    spv_const_composite,                       // llvm.spv.const.composite (IntrinsicsSPIRV.td:35)
    spv_cross,                                 // llvm.spv.cross (IntrinsicsSPIRV.td:102)
    spv_ddx,                                   // llvm.spv.ddx (IntrinsicsSPIRV.td:186)
    spv_ddx_coarse,                            // llvm.spv.ddx.coarse (IntrinsicsSPIRV.td:188)
    spv_ddx_fine,                              // llvm.spv.ddx.fine (IntrinsicsSPIRV.td:190)
    spv_ddy,                                   // llvm.spv.ddy (IntrinsicsSPIRV.td:187)
    spv_ddy_coarse,                            // llvm.spv.ddy.coarse (IntrinsicsSPIRV.td:189)
    spv_ddy_fine,                              // llvm.spv.ddy.fine (IntrinsicsSPIRV.td:191)
    spv_degrees,                               // llvm.spv.degrees (IntrinsicsSPIRV.td:103)
    spv_device_memory_barrier,                 // llvm.spv.device.memory.barrier (IntrinsicsSPIRV.td:180)
    spv_device_memory_barrier_with_group_sync,  // llvm.spv.device.memory.barrier.with.group.sync (IntrinsicsSPIRV.td:181)
    spv_discard,                               // llvm.spv.discard (IntrinsicsSPIRV.td:185)
    spv_distance,                              // llvm.spv.distance (IntrinsicsSPIRV.td:104)
    spv_dot4add_i8packed,                      // llvm.spv.dot4add.i8packed (IntrinsicsSPIRV.td:141)
    spv_dot4add_u8packed,                      // llvm.spv.dot4add.u8packed (IntrinsicsSPIRV.td:142)
    spv_expect,                                // llvm.spv.expect (IntrinsicsSPIRV.td:67)
    spv_extractelt,                            // llvm.spv.extractelt (IntrinsicsSPIRV.td:33)
    spv_extractv,                              // llvm.spv.extractv (IntrinsicsSPIRV.td:31)
    spv_faceforward,                           // llvm.spv.faceforward (IntrinsicsSPIRV.td:105)
    spv_fdot,                                  // llvm.spv.fdot (IntrinsicsSPIRV.td:129)
    spv_firstbitlow,                           // llvm.spv.firstbitlow (IntrinsicsSPIRV.td:222)
    spv_firstbitshigh,                         // llvm.spv.firstbitshigh (IntrinsicsSPIRV.td:221)
    spv_firstbituhigh,                         // llvm.spv.firstbituhigh (IntrinsicsSPIRV.td:220)
    spv_flattened_thread_id_in_group,          // llvm.spv.flattened.thread.id.in.group (IntrinsicsSPIRV.td:99)
    spv_frac,                                  // llvm.spv.frac (IntrinsicsSPIRV.td:106)
    spv_freeze,                                // llvm.spv.freeze (IntrinsicsSPIRV.td:49)
    spv_fwidth,                                // llvm.spv.fwidth (IntrinsicsSPIRV.td:192)
    spv_generic_cast_to_ptr_explicit,          // llvm.spv.generic.cast.to.ptr.explicit (IntrinsicsSPIRV.td:365)
    spv_gep,                                   // llvm.spv.gep (IntrinsicsSPIRV.td:26)
    spv_global_offset,                         // llvm.spv.global.offset (IntrinsicsSPIRV.td:87)
    spv_global_size,                           // llvm.spv.global.size (IntrinsicsSPIRV.td:86)
    spv_group_id,                              // llvm.spv.group.id (IntrinsicsSPIRV.td:83)
    spv_group_memory_barrier,                  // llvm.spv.group.memory.barrier (IntrinsicsSPIRV.td:182)
    spv_group_memory_barrier_with_group_sync,  // llvm.spv.group.memory.barrier.with.group.sync (IntrinsicsSPIRV.td:183)
    spv_init_global,                           // llvm.spv.init.global (IntrinsicsSPIRV.td:23)
    spv_inline_asm,                            // llvm.spv.inline.asm (IntrinsicsSPIRV.td:50)
    spv_insertelt,                             // llvm.spv.insertelt (IntrinsicsSPIRV.td:34)
    spv_insertv,                               // llvm.spv.insertv (IntrinsicsSPIRV.td:32)
    spv_interlocked_add,                       // llvm.spv.interlocked.add (IntrinsicsSPIRV.td:151)
    spv_interlocked_or,                        // llvm.spv.interlocked.or (IntrinsicsSPIRV.td:155)
    spv_isfinite,                              // llvm.spv.isfinite (IntrinsicsSPIRV.td:111)
    spv_isinf,                                 // llvm.spv.isinf (IntrinsicsSPIRV.td:107)
    spv_isnan,                                 // llvm.spv.isnan (IntrinsicsSPIRV.td:109)
    spv_isnormal,                              // llvm.spv.isnormal (IntrinsicsSPIRV.td:113)
    spv_length,                                // llvm.spv.length (IntrinsicsSPIRV.td:117)
    spv_lerp,                                  // llvm.spv.lerp (IntrinsicsSPIRV.td:115)
    spv_lifetime_end,                          // llvm.spv.lifetime.end (IntrinsicsSPIRV.td:75)
    spv_lifetime_start,                        // llvm.spv.lifetime.start (IntrinsicsSPIRV.td:70)
    spv_load,                                  // llvm.spv.load (IntrinsicsSPIRV.td:27)
    spv_loop_control_intel,                    // llvm.spv.loop.control.intel (IntrinsicsSPIRV.td:40)
    spv_loop_merge,                            // llvm.spv.loop.merge (IntrinsicsSPIRV.td:39)
    spv_masked_gather,                         // llvm.spv.masked.gather (IntrinsicsSPIRV.td:58)
    spv_masked_scatter,                        // llvm.spv.masked.scatter (IntrinsicsSPIRV.td:61)
    spv_named_boolean_spec_constant,           // llvm.spv.named.boolean.spec.constant (IntrinsicsSPIRV.td:51)
    spv_nclamp,                                // llvm.spv.nclamp (IntrinsicsSPIRV.td:195)
    spv_normalize,                             // llvm.spv.normalize (IntrinsicsSPIRV.td:118)
    spv_num_subgroups,                         // llvm.spv.num.subgroups (IntrinsicsSPIRV.td:91)
    spv_num_workgroups,                        // llvm.spv.num.workgroups (IntrinsicsSPIRV.td:88)
    spv_packhalf2x16,                          // llvm.spv.packhalf2x16 (IntrinsicsSPIRV.td:370)
    spv_poison,                                // llvm.spv.poison (IntrinsicsSPIRV.td:48)
    spv_ptrcast,                               // llvm.spv.ptrcast (IntrinsicsSPIRV.td:37)
    spv_pushconstant_getpointer,               // llvm.spv.pushconstant.getpointer (IntrinsicsSPIRV.td:341)
    spv_quad_read_across_diagonal,             // llvm.spv.quad.read.across.diagonal (IntrinsicsSPIRV.td:175)
    spv_quad_read_across_x,                    // llvm.spv.quad.read.across.x (IntrinsicsSPIRV.td:173)
    spv_quad_read_across_y,                    // llvm.spv.quad.read.across.y (IntrinsicsSPIRV.td:174)
    spv_radians,                               // llvm.spv.radians (IntrinsicsSPIRV.td:177)
    spv_reflect,                               // llvm.spv.reflect (IntrinsicsSPIRV.td:119)
    spv_refract,                               // llvm.spv.refract (IntrinsicsSPIRV.td:120)
    spv_resource_calculate_lod,                // llvm.spv.resource.calculate.lod (IntrinsicsSPIRV.td:311)
    spv_resource_calculate_lod_unclamped,      // llvm.spv.resource.calculate.lod.unclamped (IntrinsicsSPIRV.td:316)
    spv_resource_counterhandlefrombinding,     // llvm.spv.resource.counterhandlefrombinding (IntrinsicsSPIRV.td:215)
    spv_resource_counterhandlefromimplicitbinding,  // llvm.spv.resource.counterhandlefromimplicitbinding (IntrinsicsSPIRV.td:211)
    spv_resource_gather,                       // llvm.spv.resource.gather (IntrinsicsSPIRV.td:321)
    spv_resource_gather_cmp,                   // llvm.spv.resource.gather.cmp (IntrinsicsSPIRV.td:327)
    spv_resource_getbasepointer,               // llvm.spv.resource.getbasepointer (IntrinsicsSPIRV.td:337)
    spv_resource_getdimensions_levels_x,       // llvm.spv.resource.getdimensions.levels.x (IntrinsicsSPIRV.td:234)
    spv_resource_getdimensions_levels_xy,      // llvm.spv.resource.getdimensions.levels.xy (IntrinsicsSPIRV.td:236)
    spv_resource_getdimensions_levels_xyz,     // llvm.spv.resource.getdimensions.levels.xyz (IntrinsicsSPIRV.td:238)
    spv_resource_getdimensions_ms_xy,          // llvm.spv.resource.getdimensions.ms.xy (IntrinsicsSPIRV.td:240)
    spv_resource_getdimensions_ms_xyz,         // llvm.spv.resource.getdimensions.ms.xyz (IntrinsicsSPIRV.td:242)
    spv_resource_getdimensions_x,              // llvm.spv.resource.getdimensions.x (IntrinsicsSPIRV.td:228)
    spv_resource_getdimensions_xy,             // llvm.spv.resource.getdimensions.xy (IntrinsicsSPIRV.td:230)
    spv_resource_getdimensions_xyz,            // llvm.spv.resource.getdimensions.xyz (IntrinsicsSPIRV.td:232)
    spv_resource_getpointer,                   // llvm.spv.resource.getpointer (IntrinsicsSPIRV.td:333)
    spv_resource_handlefrombinding,            // llvm.spv.resource.handlefrombinding (IntrinsicsSPIRV.td:201)
    spv_resource_handlefromimplicitbinding,    // llvm.spv.resource.handlefromimplicitbinding (IntrinsicsSPIRV.td:206)
    spv_resource_load_level,                   // llvm.spv.resource.load.level (IntrinsicsSPIRV.td:287)
    spv_resource_load_typedbuffer,             // llvm.spv.resource.load.typedbuffer (IntrinsicsSPIRV.td:350)
    spv_resource_nonuniformindex,              // llvm.spv.resource.nonuniformindex (IntrinsicsSPIRV.td:344)
    spv_resource_sample,                       // llvm.spv.resource.sample (IntrinsicsSPIRV.td:245)
    spv_resource_sample_clamp,                 // llvm.spv.resource.sample.clamp (IntrinsicsSPIRV.td:250)
    spv_resource_samplebias,                   // llvm.spv.resource.samplebias (IntrinsicsSPIRV.td:256)
    spv_resource_samplebias_clamp,             // llvm.spv.resource.samplebias.clamp (IntrinsicsSPIRV.td:262)
    spv_resource_samplecmp,                    // llvm.spv.resource.samplecmp (IntrinsicsSPIRV.td:293)
    spv_resource_samplecmp_clamp,              // llvm.spv.resource.samplecmp.clamp (IntrinsicsSPIRV.td:299)
    spv_resource_samplecmplevelzero,           // llvm.spv.resource.samplecmplevelzero (IntrinsicsSPIRV.td:305)
    spv_resource_samplegrad,                   // llvm.spv.resource.samplegrad (IntrinsicsSPIRV.td:268)
    spv_resource_samplegrad_clamp,             // llvm.spv.resource.samplegrad.clamp (IntrinsicsSPIRV.td:274)
    spv_resource_samplelevel,                  // llvm.spv.resource.samplelevel (IntrinsicsSPIRV.td:281)
    spv_resource_store_typedbuffer,            // llvm.spv.resource.store.typedbuffer (IntrinsicsSPIRV.td:355)
    spv_resource_updatecounter,                // llvm.spv.resource.updatecounter (IntrinsicsSPIRV.td:224)
    spv_rsqrt,                                 // llvm.spv.rsqrt (IntrinsicsSPIRV.td:125)
    spv_saturate,                              // llvm.spv.saturate (IntrinsicsSPIRV.td:126)
    spv_sclamp,                                // llvm.spv.sclamp (IntrinsicsSPIRV.td:194)
    spv_sdot,                                  // llvm.spv.sdot (IntrinsicsSPIRV.td:133)
    spv_selection_merge,                       // llvm.spv.selection.merge (IntrinsicsSPIRV.td:41)
    spv_sign,                                  // llvm.spv.sign (IntrinsicsSPIRV.td:176)
    spv_smoothstep,                            // llvm.spv.smoothstep (IntrinsicsSPIRV.td:127)
    spv_step,                                  // llvm.spv.step (IntrinsicsSPIRV.td:128)
    spv_store,                                 // llvm.spv.store (IntrinsicsSPIRV.td:29)
    spv_subgroup_ballot,                       // llvm.spv.subgroup.ballot (IntrinsicsSPIRV.td:159)
    spv_subgroup_id,                           // llvm.spv.subgroup.id (IntrinsicsSPIRV.td:93)
    spv_subgroup_local_invocation_id,          // llvm.spv.subgroup.local.invocation.id (IntrinsicsSPIRV.td:95)
    spv_subgroup_max_size,                     // llvm.spv.subgroup.max.size (IntrinsicsSPIRV.td:97)
    spv_subgroup_prefix_bit_count,             // llvm.spv.subgroup.prefix.bit.count (IntrinsicsSPIRV.td:143)
    spv_subgroup_size,                         // llvm.spv.subgroup.size (IntrinsicsSPIRV.td:89)
    spv_switch,                                // llvm.spv.switch (IntrinsicsSPIRV.td:38)
    spv_thread_id,                             // llvm.spv.thread.id (IntrinsicsSPIRV.td:82)
    spv_thread_id_in_group,                    // llvm.spv.thread.id.in.group (IntrinsicsSPIRV.td:84)
    spv_track_constant,                        // llvm.spv.track.constant (IntrinsicsSPIRV.td:22)
    spv_uclamp,                                // llvm.spv.uclamp (IntrinsicsSPIRV.td:193)
    spv_udot,                                  // llvm.spv.udot (IntrinsicsSPIRV.td:137)
    spv_undef,                                 // llvm.spv.undef (IntrinsicsSPIRV.td:47)
    spv_unpackhalf2x16,                        // llvm.spv.unpackhalf2x16 (IntrinsicsSPIRV.td:369)
    spv_unreachable,                           // llvm.spv.unreachable (IntrinsicsSPIRV.td:43)
    spv_unref_global,                          // llvm.spv.unref.global (IntrinsicsSPIRV.td:24)
    spv_value_md,                              // llvm.spv.value.md (IntrinsicsSPIRV.td:20)
    spv_wave_active_countbits,                 // llvm.spv.wave.active.countbits (IntrinsicsSPIRV.td:144)
    spv_wave_all,                              // llvm.spv.wave.all (IntrinsicsSPIRV.td:146)
    spv_wave_all_equal,                        // llvm.spv.wave.all.equal (IntrinsicsSPIRV.td:145)
    spv_wave_any,                              // llvm.spv.wave.any (IntrinsicsSPIRV.td:147)
    spv_wave_get_lane_count,                   // llvm.spv.wave.get.lane.count (IntrinsicsSPIRV.td:169)
    spv_wave_is_first_lane,                    // llvm.spv.wave.is.first.lane (IntrinsicsSPIRV.td:167)
    spv_wave_prefix_product,                   // llvm.spv.wave.prefix.product (IntrinsicsSPIRV.td:172)
    spv_wave_prefix_sum,                       // llvm.spv.wave.prefix.sum (IntrinsicsSPIRV.td:171)
    spv_wave_product,                          // llvm.spv.wave.product (IntrinsicsSPIRV.td:166)
    spv_wave_readlane,                         // llvm.spv.wave.readlane (IntrinsicsSPIRV.td:168)
    spv_wave_reduce_and,                       // llvm.spv.wave.reduce.and (IntrinsicsSPIRV.td:150)
    spv_wave_reduce_max,                       // llvm.spv.wave.reduce.max (IntrinsicsSPIRV.td:162)
    spv_wave_reduce_min,                       // llvm.spv.wave.reduce.min (IntrinsicsSPIRV.td:163)
    spv_wave_reduce_or,                        // llvm.spv.wave.reduce.or (IntrinsicsSPIRV.td:148)
    spv_wave_reduce_sum,                       // llvm.spv.wave.reduce.sum (IntrinsicsSPIRV.td:165)
    spv_wave_reduce_umax,                      // llvm.spv.wave.reduce.umax (IntrinsicsSPIRV.td:161)
    spv_wave_reduce_umin,                      // llvm.spv.wave.reduce.umin (IntrinsicsSPIRV.td:164)
    spv_wave_reduce_xor,                       // llvm.spv.wave.reduce.xor (IntrinsicsSPIRV.td:149)
    spv_workgroup_size,                        // llvm.spv.workgroup.size (IntrinsicsSPIRV.td:85)
}; // enum

} // namespace llvm::Intrinsic

#endif // LLVM_IR_INTRINSIC_SPV_ENUMS_H

